### ISSUE TITLE
Widget auto-hiding of Pirate Parties lacking a particular resource

### ISSUE THREAD

**Issue by collentine** [PeterTheOne/wp-pirate-parties#14]
Currently the widget only displays those Pirate Parties that have the particular link you choose to display. e.g. Everyone has a website but not all Parties make use of Google+

Would it be possible to display all countries for all categories and just mark those that are missing a resource in some manner (or maybe just without a link) ? Alternatively have some notification on bottom stating it only shows those countries with that resource. 

Slighty problematic that the number of Pirate Parties seemingly change depending on what you show.

**Comment by PeterTheOne** [comment]
Sure. What makes more sense to you: 1. Mention that party are hidden or 2. Show them without link?

**Comment by collentine** [comment]
2 makes more sense to me

**Comment by PeterTheOne** [comment]
Do you want the notification to be in the backend widget form or as public info on the website?

Can you come up with some text? Maybe "Only parties with website/facebook/etc. are show."?

**Comment by collentine** [comment]
meant to write option number 2 (edited my comment above). Seems that Github automatically enumerates 2 (.) to 
1.  this is odd

Prefer seeing all parties just without links for those that lack that resource

**Comment by PeterTheOne** [comment]
Ok, 2 it is.
