### ISSUE TITLE
Widget display enhancements

### ISSUE THREAD

**Issue by collentine** [PeterTheOne/wp-pirate-parties#15]
Some suggestions that doesn't change function but visual parts.
- [x] Instead of a bulleted list use the country flags in front of each party (flags can be found in PAPI and should be able to link them to each country easily. Maybe we should do this in the json if needed or you can request Rok to add that feature to the API. 
- [x] when displaying website show "country - www.websiteurl.com" rather than Pirate Party Country
- [x] when displaying twitter show "country - @username"
- [x] Sorting of countries seem random?! Make it alphabetical instead?

**Comment by collentine** [comment]
- [x] Option to display links side-by side (see bottom of https://www.piratenpartei.de/ for an example of how this looks and how the flag icons display)

**Comment by collentine** [comment]
- remove the bullets. Believe the bullets don't fill any visual function. Links are more clear and looks better without the bullets in front of them

**Comment by PeterTheOne** [comment]
> Sorting of countries seem random?! Make it alphabetical instead?

Sorting works. It was only broken because of #13 bug.

**Comment by PeterTheOne** [comment]
> remove the bullets. Believe the bullets don't fill any visual function. Links are more clear and looks better without the bullets in front of them

Won't fix. This is a style choice that can be done in the theme css and I don't want to put too much style in the plugin itself.

**Comment by PeterTheOne** [comment]
>  when displaying website show "country - www.websiteurl.com" rather than Pirate Party Country
>  when displaying twitter show "country - @username"

I added a "Link dependent" option to make this work.
