### ISSUE TITLE
Request for Widget option: Add Link to PAPI 

### ISSUE THREAD

**Issue by collentine** [PeterTheOne/wp-pirate-parties#16]
Would like to see an additional link option. An ability to have the widget give links to the more detailed PAPI page of each Pirate Party. 

Widget displays all Pirate Parties with links to the party pages in PAPI. e.g. clicking 'Pirate Party Sweden' in widget would link to http://api.piratetimes.net/party/ppse

**Comment by PeterTheOne** [comment]
I will add this.

**Comment by PeterTheOne** [comment]
fixed in 0e4ed63368b9b5db1f455c8f289e458a67acd178
