### ISSUE TITLE
Shortcode improvements

### ISSUE THREAD

**Issue by collentine** [PeterTheOne/wp-pirate-parties#20]
Love the ability to include the shortcode in a post!

For the default shortcode for a country I'd rather see memberships set to false and Facebook set to true (preferably displaying facebook.com/user rather than 'Facebook'). Most times when you use a shortcode you'd like to solely focus on that party and less relevant what memberships it has. Believe membership tag comes more in handy when displaying a list of parties and can then be set manually to show. 

e.g. [pirate-party id="ppse"]

[logo] Pirate Party Sweden
Piratpartiet
www.piratpartiet.se
facebook.com/piratpartiet
@piratpartiet

Is there an ability to make an easy shortcode to display all the data on a party rather than having to set all options to 1? e.g. [pirate-party id="ppse" all="1"]

**Comment by PeterTheOne** [comment]
done. I named `all` `show-all`.
