### ISSUE TITLE
inspiration

### ISSUE THREAD

**Issue by collentine** [PeterTheOne/wp-pirate-parties#9]
Here's some old code used to build an embeddable list http://pirateparties.collentine.com/

Was thinking something similar for the wordpress plugin. An ability to choose what properties you were interested in and creating an embeddable widget from that. Using the API it should stay current when changes happen in backend.

**Comment by PeterTheOne** [comment]
Thanks for the link, I think this plugin covers most of its features already, feel free to try it.

You can display links to:
- Website
- Facebook
- Twitter
- Google+
- Youtube

What is missing is:
- IRC ( https://en.wikipedia.org/wiki/Internet_Relay_Chat#URI_scheme )
- Wiki (not in PPI-party-info repository, see https://github.com/Pirate-Parties-International/PPI-party-info/issues/12 )
- Generel Contact E-Mail ( `mailto:` )

The default behavior when for example a link to a website is missing then the party is excluded from the listing, maybe this should be changed. What do you think?
